"""
Filename: madlib.py
Author: <hensel, oliver>
Created: <08/31/2026>
Instructor: Burgess
"""
q1=("Adjective:")
q2=("Noun (Electronic Device):")
q3=("Plural Noun:")
q4=("Verb (ending in -ing):")
q5=("Noun (Website):")
q6=("Exclamation:")
q7=("Body Part:")
q8=("Name of a Person:")
q9=("Noun (Liquid):")
q10=("Type of Food:")
q11=("Number:")
q12=("Adjective:")
q13=("Noun (Programming Language):")
q14=("Verb:")
q15=("Animal:")
q16=("Noun:")
q17=("Plural Noun (Tech Items):")
q18=("Verb (ending in -ed):")
q19=("Adjective:")
q20=("Noun (Place):")

q1=input ("Adjective:")
q2=input ("Noun (Electronic Device):")
q3=input ("Plural Noun:")
q4=input ("Verb (ending in -ing):")
q5=input ("Noun (Website):")
q6=input ("Exclamation:")
q7=input ("Body Part:")
q8=input ("Name of a Person:")
q9=input ("Noun (Liquid):")
q10=input ("Type of Food:")
q11=input ("Number:")
q12=input ("Adjective:")
q13=input ("Noun (Programming Language):")
q14=input ("Verb:")
q15=input ("Animal:")
q16=input ("Noun:")
q17=input ("Plural Noun (Tech Items):")
q18=input ("Verb (ending in -ed):")
q19=input ("Adjective:")
q20=input ("Noun (Place):\n")
print ("\nIt started as a (1:",q1, ")morning at the office when my desktop (2:",q2,")suddenly \nemitted a puff of green smoke. On the screen, thousands of (3:",q3,") began")
print ("(4:",q4,") across the desktop. I tried loading (5:", q5,") to look for help, but the browser crashed instantly.")
print ("\n\"(6:",q6,")!\" I screamed, slapping my (7:", q7,") in frustration.")
print ("\nI called over (8:",q8,"),our IT specialist, who arrived holding a mug of warm (9:",q9,")")
print ("and half-eaten (10:",q10,"). They stared at the machine for (11:",q11,") minutes with a very (12:",q12,")look on their face.")
print ("\"The mainframe is completely infected with a rogue script written in (13:",q13,"),\" \nthey explained. \"We need to (14:",q14,")the motherboard before it triggers the fire alarms!\"")
print ("Suddenly, the computer speaker started making noises like a wild (15:",q15,"). \nThe disc drive shot out a glossy (16:",q16,"),\n followed by a barrage of loose (17:",q17,")that flew across the room. I (18:",q18,")out of the way just in time!")
print ("Thanks to our quick thinking, the office stayed completely (19:",q19,"), \nbut I decided to do the rest of my work today from the comfort of the local (20:",q20,").")