print ("welcome to the interview")
h_self=("alright thats great")
input("question one\ntell me about yourself")
print(h_self)
h_weakness=("great")
input("question two,\nwhat are you're strengths and weaknesses?")
print(h_weakness)
h_hire=("okay.")
input("question 3 \nwhy should we hire you?")
print(h_hire)
h_challenge=("fantastic, last question")
input("question 4 \ntell me about a time you've overcame a challenge")
print(h_challenge)
h_work=("alright, thank you for your time. your interview will be recorded and processed. \ntime to hear back: 2-3 weeks")
input("question 5 \n why do you want to work here?")
print(h_work)